<%@ page pageEncoding = "utf-8"%>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="imagetoolbar" content="no" />
<link rel="stylesheet" href="common/styles/layout.css" type="text/css" />
<!-- ####################################################################################################### -->
<div class="wrapper row4">
  <div id="footer" class="clear">
    <!-- ####################################################################################################### -->
    <div class="footbox">
      <h2>快速链接</h2>
      <ul>
       <li> <a href="allpublicnotice.action">&raquo;首页</a></li>
        <li><a href="Allcontent.action">&raquo;留言版</a></li>
        <li><a href="allpassforuminfo.action?tag=4">&raquo;论坛</a></li>
        <li><a href="loaddownall.action">&raquo;下载区</a></li>
        <li><a href="#">&raquo;网站向导</a></li>
      </ul>
    </div>
    <div class="footbox">
      <h2>联系我们</h2>
      <address>
      北京市<br />
       海淀区  <br />
  065201<br />
      <br />
      Tel: 010-3234567<br />
      Email: <a href="www.126.com">chaxiansiyi@126.com</a>
      </address>
    </div>
    <div class="fl_right">
      <div id="social">
        <h2>站内链接</h2>
        <ul>
          <li><a href="http://www.facebook.com"><img src="common/images/social/facebook.gif" alt="" /></a></li>
          <li><a href="http://www.twitter.com"><img src="common/images/social/twitter.gif" alt="" /></a></li>
          <li><a href="#"><img src="common/images/social/flickr.gif" alt="" /></a></li>
          <li><a href="http://www.youtube.com"><img src="common/images/social/youtube.gif" alt="" /></a></li>
          <li class="last"><a href="#"><img src="common/images/social/rss.gif" alt="" /></a></li>
        </ul>
      </div>
      <div id="newsletter" class="clear">
        <form action="http://www.baidu.com" method="post">
          <fieldset>
            <legend>站内链接:</legend>
            <input type="text" id="subscribe" value="" onfocus="this.value=(this.value=='Enter Email Here&hellip;')? '' : this.value ;" />
            <input type="submit" id="subscribe" value="百度" />
          </fieldset>
        </form>
      </div>
    </div>
    <!-- ####################################################################################################### -->
  </div>
</div>
<!-- ####################################################################################################### -->
<div class="wrapper">
  <div id="copyright" class="clear">
    <p class="fl_left">Copyright &copy; 2014 - All Rights Reserved - <a href="#">王惠</a></p>
  </div>
</div>
</body>
</html>